### PR TITLE
Add `treeCollideAction` config and minor fixes / tidy up

### LINKED ISSUE #118: Reconsider tree generation
There are 3 ways of handling overlapping trees:
1. Placing the tree anyway: easiest method to do, don't need to check collision, fastest. However, this could result in very weird-looking tree-like structures
2. Not placing the tree: Requires checking collision (still simpler that with 3.) and may result in less trees per chunk but doesn't result in weird stuff like in 1.
3. Only placing trees where it doesn't overlap: Most complicated (and slowest) but guarantees that the number of trees is the same as desired while still not allowing trees to overlap. When considering visible features, this is the best option but it is also the most complicated. This is the current method but it could be much more efficient (see https://github.com/MarcellPerger1/minecraft_clone_1/issues/95#issuecomment-1204252985)

- [ ] Decide which one to do (or add a config)
- [ ] Implement it (or in the case of option 3. decide whether to make it faster)

### PR DESCRIPTION
**Pull request by MarcellPerger1**
- Add `treeCollideAction` config (fixes #118)
- Allow highlighting `dyn_info` text
- Fix some errors when compiling with `tsc --allowJs --checkJs`
- Add more prefetches
- `BaseGenerator` class as a base class for classes involved in world generation
- Remove some old unused stuff

### CODE REVIEW

File: src/world/generation.js [hunk 1]
```diff
@@ -4,18 +4,18 @@ import { rangeList } from "../utils.js";
...
   constructor(game) {
     super(game);
     this.init();
     this.baseTerrain = new OctaveNoise(
-      this.gcnf.seed, "base-terrain", this.gcnf.baseTerrain, n => -n.minValue());
+      this.gcnf.seed, "base-terrain", this.gcnf.baseTerrain, n => -n.minRawValue());
     this.stoneOffset = new OctaveNoise(
       this.gcnf.seed, "stone-offset", this.gcnf.stoneOffset, -3);
-    this.treeGetter = new TreePosGetter(this.gcnf.seed, this.wSize[0], this.wSize[2], this.gcnf.nTrees, this.gcnf.treeRadius);
+    this.treeGetter = new AvoidTreePlacer(this.gcnf.seed, this.wSize[0], this.wSize[2], this.gcnf.nTrees, this.gcnf.treeRadius);
```
Comment (MarcellPerger1) [inline src/world/generation.js:18]: Should use new `TreePlacer` for trees

File: src/renderer/renderer.js [hunk 2]
```diff
@@ -148,7 +148,6 @@ export class Renderer extends GameComponent {
   
   // DRAW SCENE
   renderFrame(remakeMesh){
```
Comment (MarcellPerger1) [inline src/renderer/renderer.js:150]: This isn't even called with an argument any more so the parameter is not needed at all

File: src/world/tree_generation.js [hunk 3]
```diff
@@ -1,10 +1,107 @@
...
+   */
+  coordToIdx(x, z) {
+    return this.wSize[0] * z + x;
+  }
+}
+
 
-export class TreePosGetter {
+export class AvoidTreePlacer {
   constructor(seed, x, z, n_trees, treeRadius) {
```
Comment (MarcellPerger1) [inline src/world/tree_generation.js:105]: Does this really need this many arguments? It would be cleaner just to pass the `Game` object (or the `TreePlacer` object) and extract the needed attributes from that object.

File: src/world/tree_generation.js [hunk 4]
```diff
@@ -1,20 +1,112 @@
...
+}
+
+
+export class SkipTreePlacer extends BaseGenerator {
+  constructor(game) {
+    super(game);
+    this.n = this.wSize[0] * this.wSize[2];
+    this.seed = this.getSeed("tree-pos", 0);
+    this.rng = alea(this.seed);
+    let w = this.gcnf.treeRadius[0];
```
Comment (MarcellPerger1) [inline src/world/tree_generation.js:59]: There is a lot of common functionality & duplicated code between the 3 tree placers. Perhaps make a `BaseTreeGenerator` class have have them inherit from it.

File: src/libs/alea/alea.js [hunk 5]
```diff
@@ -13,13 +13,13 @@ Modified again by Marcell Perger.
  * @prop {(lo: number, hi: number) => number} randint
  */
 /**
- * @typedef {(RandomNS & () => number)} Random
+ * @typedef {(RandomNS & (() => number))} Random
```
Comment (MarcellPerger1) [inline src/libs/alea/alea.js:16]: This file is marked as generated in `.gitattributes` - should probably not be

Comment (MarcellPerger1) [reply src/libs/alea/alea.js:16]: Or just move it out of this directory. I should to make an issue for this and do a separate pull request.
